name: default

channels:
  - conda-forge
  - nodefaults

dependencies:
  - black
  - flit >=3.9,<4
  - jupyterlab >=4,<5
  - nodejs >=18,<19
  - notebook >=7,<8
  - pip
  - python-build
  - ruff
  - twine
